# Spring 配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: root
  # 模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    # 非规范html
    mode: LEGACYHTML5
    encoding: utf-8
    content-type: text/html
    cache: false
  # 静态资源配置
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  # 邮箱服务配置
  mail:
    host: smtp.163.com
    port: 25
    username: bengangxue@163.com
    password: m2015214296
  # Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 30000
    pool:
      max-active: 2000
      max-wait: 6000
      min-idle: 100
      max-idle: 300


